#!/usr/bin/env bash
#
# bootstrap_toolchain.sh
# ----------------------
# Installs a build toolchain (cmake + CUDA compiler + gcc/g++) entirely in
# USERSPACE — no sudo, no root, no system package manager. It uses micromamba
# (a single static binary) to create a self-contained conda environment under
# ./toolchain, and writes ./toolchain/activate.sh so setup_and_run.sh can pick
# it up automatically.
#
# Run this ONCE on the GPU node when `cmake` / `nvcc` are not available:
#   chmod +x bootstrap_toolchain.sh
#   ./bootstrap_toolchain.sh
# then run ./setup_and_run.sh as usual.
#
# Requires only: a shell, curl (or wget), and internet access on the node.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_DIR="$PROJECT_DIR/toolchain"
MAMBA_DIR="$PROJECT_DIR/.micromamba"
MAMBA="$MAMBA_DIR/bin/micromamba"

# CUDA toolkit version. 12.8+ is required for Blackwell (RTX 50-series /
# RTX PRO 6000 Blackwell, sm_120). Override: CUDA_VERSION=12.6 ./bootstrap_toolchain.sh
CUDA_VERSION="${CUDA_VERSION:-12.8}"
# conda platform; this cluster's GPU nodes are x86_64.
MAMBA_PLATFORM="${MAMBA_PLATFORM:-linux-64}"

log()  { printf '\033[1;36m[bootstrap]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[error]\033[0m %s\n' "$*" >&2; }

command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || {
  err "Need curl or wget to download micromamba."; exit 1; }

# 1. Fetch micromamba (static binary; no install/root needed) ---------------
if [[ ! -x "$MAMBA" ]]; then
  log "Downloading micromamba ($MAMBA_PLATFORM) ..."
  mkdir -p "$MAMBA_DIR"
  url="https://micro.mamba.pm/api/micromamba/$MAMBA_PLATFORM/latest"
  if command -v curl >/dev/null 2>&1; then
    curl -Ls "$url" | tar -xj -C "$MAMBA_DIR" bin/micromamba
  else
    wget -qO- "$url" | tar -xj -C "$MAMBA_DIR" bin/micromamba
  fi
fi
[[ -x "$MAMBA" ]] || { err "micromamba download failed."; exit 1; }
log "micromamba: $("$MAMBA" --version)"

# 2. Create the toolchain environment ---------------------------------------
export MAMBA_ROOT_PREFIX="$MAMBA_DIR/root"
log "Creating toolchain env at $ENV_DIR (cmake, ninja, gcc/g++, CUDA $CUDA_VERSION) ..."
log "This downloads a few GB and takes a few minutes."
"$MAMBA" create -y -p "$ENV_DIR" \
  -c conda-forge -c nvidia \
  cmake ninja make gcc gxx \
  cuda-toolkit "cuda-version=$CUDA_VERSION"

# 3. Write an activation snippet setup_and_run.sh can source ----------------
cat > "$ENV_DIR/activate.sh" <<EOF
# Auto-generated by bootstrap_toolchain.sh — adds the userspace toolchain to PATH.
export CUDA_HOME="$ENV_DIR"
export PATH="$ENV_DIR/bin:\$PATH"
export CUDACXX="$ENV_DIR/bin/nvcc"
# Use the env's gcc/g++ so they match the CUDA toolkit version.
export CC="$ENV_DIR/bin/gcc"
export CXX="$ENV_DIR/bin/g++"
EOF

# 4. Sanity check ------------------------------------------------------------
# shellcheck disable=SC1090
source "$ENV_DIR/activate.sh"
log "cmake : $(command -v cmake)  ($(cmake --version | head -1))"
log "nvcc  : $(command -v nvcc)   ($(nvcc --version | grep -i release || true))"

cat <<EOF

$(printf '\033[1;32m[done]\033[0m') Userspace toolchain ready in ./toolchain
setup_and_run.sh will source ./toolchain/activate.sh automatically. Just run:

  ./setup_and_run.sh

(To use this toolchain in your own shell:  source ./toolchain/activate.sh)
EOF
